// LOGIN ACTIONS
export const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';

//POSTS ACTIONS
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';
export const GET_POSTS_PENDING = 'GET_POSTS_PENDING';

//CURRENT USER ACTIONS
export const GET_CURRENT_USER_PENDING = 'GET_CURRENT_USER_PENDING';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED';

//GET STATUS INFO
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS';
export const GET_STATUS_FAILED = 'GET_STATUS_FAILED';
export const GET_STATUS_PENDING = 'GET_STATUS_PENDING';

//DELETE STATUS INFO
export const DELETE_STATUS_SUCCESS = 'DELETE_STATUS_SUCCESS';